### ISSUE TITLE
Failed to connect to HA

### ISSUE THREAD

**Issue by Simoverdex** [cgiesche/streamdeck-homeassistant#64]
Hi everyone,
i'm trying this plugin but i can't connect with my HA.
MacMini osx10.15.7
Stream Deck Version: 5.1.3 (14750)
HA: Home Assistant OS 2021.12.2

The error I get on Stream Deck is "Failed to connect to ws: //...etc"
while going into the system log of HA I get this error:

2021-12-16 15:09:57 ERROR (MainThread) [aiohttp.server] Unhandled exception
Traceback (most recent call last):
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1183, in _sendfile_fallback
read = await self.run_in_executor(None, file.readinto, view)
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 514, in start
resp, reset = await task
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 460, in _handle_request
reset = await self.finish_response(request, resp, start_time)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 613, in finish_response
await prepare_meth(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_fileresponse.py", line 286, in prepare
return await self._sendfile(request, fobj, offset, count)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_fileresponse.py", line 99, in _sendfile
await loop.sendfile(transport, fobj, offset, count)
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1162, in sendfile
return await self._sendfile_fallback(transport, file,
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1192, in _sendfile_fallback
await proto.restore()
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 263, in restore
self._transport.resume_reading()
File "/usr/local/lib/python3.9/asyncio/sslproto.py", line 343, in resume_reading
self._ssl_protocol._transport.resume_reading()
AttributeError: 'NoneType' object has no attribute 'resume_reading'

**Comment by Simoverdex** [comment]
UPDATE. I tried to disable the SSL certificate, removing these entries from the config.yaml:
   ssl_certificate: /ssl/fullchain.pem
   ssl_key: /ssl/privkey.pem

With the SSL Certificate disabled the Stream Deck plugin works, it connects and I can turn my lights on or off. Unfortunately when I reactivate it it no longer works. Any suggestions?

**Comment by cgiesche** [comment]
Hi,

i am using the plugin with Home-Assistant behind an SSL reverse proxy with an "official" LetsEncrypt certificate. So in general, SSL secured connections should work.

StreamDeck is using Chromium as engine for their StreamDeck app. Maybe, if you are using a self signed certificate, chromium does not accept it. In this case, there is no way around it, because I can not change the internal settings of Stream-Deck's chromium engine.

I hope this helps

**Comment by Simoverdex** [comment]
Hi, I also use a Let’s Encrypt certificate, am I wrong somewhere else?

**Comment by cgiesche** [comment]
Hmm, did you prefix your home assistant url with "wss://"?
ws = plain websocket
wss = with ssl

**Comment by Simoverdex** [comment]
I tried both prefixes, both ws and wss with local address and with dns. Port forwarding is okay.

**Comment by cgiesche** [comment]
Sorry, I was busy doing intense real life :)

Unfortunately i have no idea, what could be wrong with your setup. 

If you are familiar witth chrome's developers tools, you could try to take a look at the logging / debug information from stream deck plugin: https://developer.elgato.com/documentation/stream-deck/sdk/create-your-own-plugin/#debugging.

**Comment by hefas** [comment]
I was having same issue because the documentation suggested not specifying a port with SSL but it works after I specified my port which was 8123. 

example:

wss://your-address-of-home-assistant.duckdns.org:8123/api/websocket

**Comment by cgiesche** [comment]
I will update the documentation to make it more clearly. Thanks for your input!
